# Generated by Django 2.2 on 2024-03-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
